services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: x3ui-tg-bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
