version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: x3ui_tg_bot
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ./run.sh
